stages:
  - gcc
  - clang

cache:
  paths:
  - apt-cache/


gcc:
  stage: gcc
  script:
    - sudo apt-get -o dir::cache::archives="apt-cache" update && sudo apt-get -o dir::cache::archives="apt-cache" install -y build-essential wget
    - tools/10_get_fructose.sh
    - make
    - make test
    - make install
    - cd example
    - make
    - make test
  artifacts:
    paths:
    - AdsLib-Linux.a

clang:
  stage: clang
  script:
    - sudo apt-get -o dir::cache::archives="apt-cache" update && sudo apt-get -o dir::cache::archives="apt-cache" install -y build-essential clang wget
    - tools/10_get_fructose.sh
    - make CXX=/usr/bin/clang++
    - make CXX=/usr/bin/clang++ test
    - make install
    - cd example
    - make CXX=/usr/bin/clang++
    - make CXX=/usr/bin/clang++ test
  artifacts:
    paths:
    - AdsLib-Linux.a
