stages:
  - build
  - test

cache:
  paths:
  - apt-cache/

.build-template: &build-template
  stage: build
  tags:
    - docker
  image: lbs1:5500/beckhoff/docker-mxe
  script:
    - tools/10_get_fructose.sh
    - make CXX=$compiler OS_NAME=$os_name
    - make CXX=$compiler OS_NAME=$os_name AdsLibTest.bin
    - make OS_NAME=$os_name install
    - cd example
    - make CXX=$compiler OS_NAME=$os_name
    - make CXX=$compiler OS_NAME=$os_name example.bin
  artifacts:
    paths:
    - AdsLib-$os_name.a
    - AdsLibTest.bin
    - example/example.bin

test:
  tags:
    - kvm
  stage: test
  before_script:
    - sudo apt-get -o dir::cache::archives="apt-cache" update && sudo apt-get -o dir::cache::archives="apt-cache" install -y nmap
  script:
    - ./tools/90_run_tests.sh
  dependencies:
    - build:gcc

build:gcc:
  <<: *build-template
  variables:
    compiler: /usr/bin/g++
    os_name: Linux

build:clang:
  <<: *build-template
  variables:
    compiler: /usr/bin/clang++
    os_name: Linux

build:mxe:
  <<: *build-template
  variables:
    compiler: /mxe/usr/bin/i686-w64-mingw32.static.posix-g++
    os_name: win32
